#!/bin/bash

# php5  - PHP 5.2.x
# php53 - PHP 5.3.x
# php54 - PHP 5.4.x
# php55 - PHP 5.5.x

PHP=php53

if [ -f "./php.ini" ]; then
                PHPRC="./"
        else
                PHPRC="/hsphere/shared/apache/conf/${PHP}"
fi

PHP_FCGI_CHILDREN=0
PHP_FCGI_MAX_REQUEST=100

export env PHPRC PHP_FCGI_MAX_REQUEST PHP_FCGI_CHILDREN
exec /hsphere/shared/${PHP}/bin/php-cgi

